#!/usr/bin/env bash

set -euo pipefail

##? Setups the environment
#?? 1.0.0
##?
##? Usage:
##?    install

echo "🚀 Welcome to the neftaio/dotfiles installer!"
echo "    Thanks to rgomezcasas/dotfiles             "
echo "-------------------------------------------------"
echo
read -rp "🤔  Where do you want to clone the dotfiles? (default ~/.dotfiles): " DOTFILES_PATH
echo
#DOTFILES_PATH="${DOTFILES_PATH:-~/.dotfiles}"
export DOTFILES_PATH="$HOME/.dotfiles"
echo "👉  Cloning into: '$DOTFILES_PATH'"

git clone --recursive --depth 1 git@github.com:neftaio/dotfiles.git "$DOTFILES_PATH"

"$DOTFILES_PATH/bin/dot" self install
